#!/usr/bin/env bash

##############################################################################
##
##  Upload gradle_plugins to TT Nexus (https://wiki.bytedance.net/pages/viewpage.action?pageId=173661094)
##  http://git.bytedance.com:8081/#browse/browse/components:ugc_android    （search key : com.tellh.me.ele）
##
##############################################################################

PLUGIN_VERSION="1.0.6.10"

#lancet-plugin
mvn deploy:deploy-file -DgroupId=com.tellh.me.ele -DartifactId=lancet-plugin -Dversion=$PLUGIN_VERSION -Dpackaging=jar -Dfile=./gradle_plugins/com/tellh/me/ele/lancet-plugin/$PLUGIN_VERSION/lancet-plugin-$PLUGIN_VERSION.jar -Durl=http://git.bytedance.com:8081/nexus/content/repositories/ugc_android/ -DrepositoryId=ugc_android

#lancet-weaver
mvn deploy:deploy-file -DgroupId=com.tellh.me.ele -DartifactId=lancet-weaver -Dversion=$PLUGIN_VERSION -Dpackaging=jar -Dfile=./gradle_plugins/com/tellh/me/ele/lancet-weaver/$PLUGIN_VERSION/lancet-weaver-$PLUGIN_VERSION.jar -Durl=http://git.bytedance.com:8081/nexus/content/repositories/ugc_android/ -DrepositoryId=ugc_android

#lancet-base
mvn deploy:deploy-file -DgroupId=com.tellh.me.ele -DartifactId=lancet-base -Dversion=$PLUGIN_VERSION -Dpackaging=jar -Dfile=./gradle_plugins/com/tellh/me/ele/lancet-base/$PLUGIN_VERSION/lancet-base-$PLUGIN_VERSION.jar -Durl=http://git.bytedance.com:8081/nexus/content/repositories/ugc_android/ -DrepositoryId=ugc_android