#!/usr/bin/env bash

##############################################################################
##
##  Upload gradle_plugins to TT Nexus (https://wiki.bytedance.net/pages/viewpage.action?pageId=173661094)
##  http://git.bytedance.com:8081/#browse/browse/components:ugc_android    （search key : com.tellh.me.ele）
##  1.修改gradle.properties 版本号
##  2.执行本脚本，推送到nexus仓库
##
##############################################################################

rm -rf ./gradle_plugins

echo "uploadToNexus=false" > upload.properties

./gradlew :lancet-base:clean
./gradlew :lancet-base:build
./gradlew :lancet-base:uploadArchives

./gradlew :lancet-weaver:clean
./gradlew :lancet-weaver:build
./gradlew :lancet-weaver:uploadArchives

./gradlew :lancet-plugin:clean
./gradlew :lancet-plugin:build
./gradlew :lancet-plugin:uploadArchives

rm -rf ./upload.properties




